server:
  port: 8081

spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://localhost:3306/customer_db?createDatabaseIfNotExist=true
    username: root
    password: Naren@123
    #driverClassName: com.mysql.jdbc.Driver
     #Hibernate
     #The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #Dilect - Generate Query
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl: update
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true


